spring:
  application:
    name: job-matching-service

server:
  port: ${SERVER_PORT:8097}

services:
  application-tracker-service:
    base-url: ${APPLICATION_TRACKER_SERVICE_BASE_URL:http://localhost:8088}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] [%X{serviceName}] [%thread] %logger{36} - %msg%n"
  level:
    com.jobseekercopilot: ${APP_LOG_LEVEL:INFO}
